server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles:
    active: eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka2:8762/eureka/
