spring:
  application:
    name: trace-1
#  zipkin:
#    base-url: http://localhost:9411
  rabbitmq:
    host: 10.201.17.154
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9101
