server:
  port: 9003

spring:
  application:
    name: api-geteway

# 面向服务的路由
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: base-service
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
