logging:
  file:
    name: spring.log
    path: /log/
    max-size: 100MB
    max-history: 7
  pattern:

    level: user:%X{user} %5p
  group:
    # 自己定义日志组
    tomcat:
      org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level:
    root:
      debug
    tomcat:
      TRACE
